# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://gaul.co.in
title: Gaul Coin
email: info@gaul.co.in
author: Admin
description: > # "Write an awesome description for your new site here. 
  GAUL is a Cryptocurrency that can be earned by staking. Investors can participate via GAUL Reward Program or Investbox.
copyright: 'Copyright &copy; 2020 Gaul COin. All Rights Reserved.'
credits: 'Credits: Theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/GaulCoin
  - title: github
    url: https://github.com/gaulcoin
  - title: 
    url: 
